spring.application.name=life-replay-ai

# ===============================
# SERVER CONFIG
# ===============================
server.port=8081


# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/aiproject
#spring.datasource.username=root
#spring.datasource.password=9661

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

upload.dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#cloudinary.cloud-name=dqsggacvp
#cloudinary.api-key=294247931847361
#cloudinary.api-secret=r_BnYviQ6xBNzQsCebVdrwpDHdQ

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}





